### ISSUE TITLE
Some unlisted projects

### ISSUE THREAD

**Issue by m4tiz5zktonj** [bombsimon/awesome-garmin#32]
Hi!

Here are CIQ projects from my bookmarks. Not that I reviewed them all and can guarantee their quality, but you may want to add at least some of them.

Barrel
https://github.com/douglasr/ciqtools-cryptography
https://github.com/douglasr/ciqtools-graphing
https://github.com/douglasr/ciqtools-number-picker
https://github.com/douglasr/msgpack-monkeyc

Watch-app
https://github.com/chakflying/flight-watcher
https://github.com/fabrikant/RoseOfWind

Watch-face
https://github.com/chakflying/tactix-fenix
https://github.com/dryotta/garmin-watchface-40d-mip-power
https://github.com/fabrikant/FontLessFace
https://github.com/fabrikant/LowEnergyFace2
https://github.com/fabrikant/WWF4
https://github.com/fabrikant/WWF5
https://github.com/markdotai/m1
https://github.com/markdotai/m2
https://github.com/shbumba/SimplePixels

Widget
https://github.com/fabrikant/AllSensors
https://github.com/fabrikant/DonnerWetter
https://github.com/fabrikant/Galendar
https://github.com/fabrikant/LetMeIn
https://github.com/fabrikant/SensorHistoryWidget

Misc
https://github.com/4ch1m/mb_runner
https://github.com/cedric-dufour/connectiq-sdk-docker
https://github.com/douglasr/connectiq-samples
https://github.com/markdotai/m2font
https://github.com/waterkip/connectiq-sdk-docker

Thanks for your work!

**Comment by bombsimon** [comment]
Lovely, thanks, and thanks for sorting the items!

I also haven't vetted every item in the list 🙈 The readme originally said "A curated list" but I changed that to "An extensive list" because to be fair, it's not very curated. I think the sorting of activity helps compensate that.

With that said, I think we can just add all of them!
